name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - name: Remove Maven config forcing settings.xml
        run: sed -i '/-s.mvn\/settings.xml/d' .mvn/maven.config
      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml
      - name: Publish Docker
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: liuweijian/webstack
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}